/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderItem = IDL.Record({
  'menuItemName' : IDL.Text,
  'variantType' : IDL.Nat,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
  'menuItemId' : IDL.Nat,
  'subtotal' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'tableNumber' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'statusCode' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const DailySummary = IDL.Record({
  'orderCount' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'price1' : IDL.Nat,
  'price2' : IDL.Nat,
});

export const idlService = IDL.Service({
  'cancelOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'clearAllOrders' : IDL.Func([], [], []),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem)],
      [IDL.Nat],
      [],
    ),
  'getActiveOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getDailySummary' : IDL.Func([IDL.Text], [DailySummary], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderItem = IDL.Record({
    'menuItemName' : IDL.Text,
    'variantType' : IDL.Nat,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
    'menuItemId' : IDL.Nat,
    'subtotal' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'tableNumber' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'statusCode' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const DailySummary = IDL.Record({
    'orderCount' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'price1' : IDL.Nat,
    'price2' : IDL.Nat,
  });
  
  return IDL.Service({
    'cancelOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'clearAllOrders' : IDL.Func([], [], []),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem)],
        [IDL.Nat],
        [],
      ),
    'getActiveOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getDailySummary' : IDL.Func([IDL.Text], [DailySummary], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };