/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailySummary { 'orderCount' : bigint, 'totalRevenue' : bigint }
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'price1' : bigint,
  'price2' : bigint,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'createdAt' : bigint,
  'description' : string,
  'tableNumber' : string,
  'totalAmount' : bigint,
  'statusCode' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'menuItemName' : string,
  'variantType' : bigint,
  'quantity' : bigint,
  'unitPrice' : bigint,
  'menuItemId' : bigint,
  'subtotal' : bigint,
}
export interface _SERVICE {
  'cancelOrder' : ActorMethod<[bigint], boolean>,
  'clearAllOrders' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<
    [string, string, string, Array<OrderItem>],
    bigint
  >,
  'getActiveOrders' : ActorMethod<[], Array<Order>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getDailySummary' : ActorMethod<[string], DailySummary>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'updateOrderStatus' : ActorMethod<[bigint, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];